<?php

if ( function_exists( 'acf_add_local_field_group' ) ):

	acf_add_local_field_group( array(
		'key'                   => 'group_5a23088caeaad',
		'title'                 => 'Become a Member',
		'fields'                => array(
			array(
				'key'               => 'field_5a2308cc7917f',
				'label'             => 'Membership Copy',
				'name'              => 'membership_copy',
				'type'              => 'textarea',
				'instructions'      => 'Copy leading into the form enticing visitors to become a member',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => 4,
				'new_lines'         => '',
			),
			array(
				'key'               => 'field_5a2308a209e8e',
				'label'             => 'Membership Form Link',
				'name'              => 'membership_form_link',
				'type'              => 'text',
				'instructions'      => 'Code to automatically load form created in GravityForms. If you need to make a change there, find the form in the GravityForms plugin.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'page',
					'operator' => '==',
					'value'    => '8',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => array(
			0 => 'the_content',
		),
		'active'                => 1,
		'description'           => 'Page section with membership form & information',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5a2626fca3ee2',
		'title'                 => 'Committees List',
		'fields'                => array(
			array(
				'key'               => 'field_5a2626fca8192',
				'label'             => 'Committees',
				'name'              => 'Committees',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'collapsed'         => '',
				'min'               => 0,
				'max'               => 0,
				'layout'            => 'table',
				'button_label'      => 'Add Issue',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5a2626fcaa33a',
						'label'             => 'Committee Name',
						'name'              => 'Committee_name',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_5a2626fcaa3e8',
						'label'             => 'Committee Description',
						'name'              => 'Committee_description',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'maxlength'         => '',
						'rows'              => '',
						'new_lines'         => '',
					),
					array(
						'key'               => 'field_5a26274d5040a',
						'label'             => 'Image',
						'name'              => 'image',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
						'preview_size'      => 'thumbnail',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'page',
					'operator' => '==',
					'value'    => '77',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => array(
			0 => 'the_content',
		),
		'active'                => 1,
		'description'           => 'Page section on issues',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5a24ef0f29c58',
		'title'                 => 'Cross-Site Links',
		'fields'                => array(
			array(
				'key'               => 'field_5a24ef1253f38',
				'label'             => 'Headline Description',
				'name'              => 'headline-description',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5a24f56b633e1',
				'label'             => 'Links',
				'name'              => 'links',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5a24f5d377858',
						'label'             => 'Link 1',
						'name'              => 'link_1',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'block',
						'sub_fields'        => array(
							array(
								'key'               => 'field_5a24f5d377859',
								'label'             => 'Headline',
								'name'              => 'headline',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							),
							array(
								'key'               => 'field_5a24f5d37785a',
								'label'             => 'Copy',
								'name'              => 'copy',
								'type'              => 'textarea',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'maxlength'         => '',
								'rows'              => '',
								'new_lines'         => '',
							),
							array(
								'key'               => 'field_5a24f5d37785b',
								'label'             => 'Link',
								'name'              => 'link',
								'type'              => 'link',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
							),
						),
					),
					array(
						'key'               => 'field_5a24f5160bb74',
						'label'             => 'Link 2',
						'name'              => 'link_2',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'block',
						'sub_fields'        => array(
							array(
								'key'               => 'field_5a24f5160bb75',
								'label'             => 'Headline',
								'name'              => 'headline',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							),
							array(
								'key'               => 'field_5a24f5160bb76',
								'label'             => 'Copy',
								'name'              => 'copy',
								'type'              => 'textarea',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'maxlength'         => '',
								'rows'              => '',
								'new_lines'         => '',
							),
							array(
								'key'               => 'field_5a24f5160bb77',
								'label'             => 'Link',
								'name'              => 'link',
								'type'              => 'link',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
							),
						),
					),
					array(
						'key'               => 'field_5a24f5200bb78',
						'label'             => 'Link 3',
						'name'              => 'link_3',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'block',
						'sub_fields'        => array(
							array(
								'key'               => 'field_5a24f5200bb79',
								'label'             => 'Headline',
								'name'              => 'headline',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							),
							array(
								'key'               => 'field_5a24f5200bb7a',
								'label'             => 'Copy',
								'name'              => 'copy',
								'type'              => 'textarea',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'maxlength'         => '',
								'rows'              => '',
								'new_lines'         => '',
							),
							array(
								'key'               => 'field_5a24f5200bb7b',
								'label'             => 'Link',
								'name'              => 'link',
								'type'              => 'link',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
							),
						),
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'page',
					'operator' => '==',
					'value'    => '10',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => array(
			0 => 'the_content',
		),
		'active'                => 1,
		'description'           => '3-column section of cross-site links',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5a2641677adf9',
		'title'                 => 'Hero',
		'fields'                => array(
			array(
				'key'               => 'field_5a2642602dff2',
				'label'             => 'Hero Message',
				'name'              => 'hero_message',
				'type'              => 'wysiwyg',
				'instructions'      => 'Highlight words by selecting and applying the "Header Highlight" style in the formatting dropdown below.
Ignore all other formatting tools here...they won\'t do anything.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'tabs'              => 'visual',
				'toolbar'           => 'full',
				'media_upload'      => 0,
				'delay'             => 0,
			),
			array(
				'key'               => 'field_5a2642b12dff3',
				'label'             => 'CTA Links',
				'name'              => 'cta_links',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5a2642c22dff4',
						'label'             => 'Link 1',
						'name'              => 'link_1',
						'type'              => 'link',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
					),
					array(
						'key'               => 'field_5a2642d42dff5',
						'label'             => 'Link 2',
						'name'              => 'link_2',
						'type'              => 'link',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'page',
					'operator' => '==',
					'value'    => '6',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => array(
			0 => 'the_content',
		),
		'active'                => 1,
		'description'           => '',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5a24fa464d931',
		'title'                 => 'Issues List',
		'fields'                => array(
			array(
				'key'               => 'field_5a24fa4ad5bd3',
				'label'             => 'Issues',
				'name'              => 'issues',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'collapsed'         => '',
				'min'               => 0,
				'max'               => 0,
				'layout'            => 'table',
				'button_label'      => 'Add Issue',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5a24fb7ad5bd4',
						'label'             => 'Issue Name',
						'name'              => 'issue',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_5a24fb8fd5bd5',
						'label'             => 'Issue Description',
						'name'              => 'issue_description',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'tabs'              => 'visual',
						'toolbar'           => 'basic',
						'media_upload'      => 0,
						'delay'             => 0,
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'page',
					'operator' => '==',
					'value'    => '10',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => array(
			0 => 'the_content',
		),
		'active'                => 1,
		'description'           => 'Page section on issues',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5a23065d63e57',
		'title'                 => 'Lead-in',
		'fields'                => array(
			array(
				'key'               => 'field_5a22fdfe98ee6',
				'label'             => 'Main Heading',
				'name'              => 'lead-in_heading',
				'type'              => 'textarea',
				'instructions'      => 'Make this engaging and exciting (and short)!',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => 1,
				'new_lines'         => '',
			),
			array(
				'key'               => 'field_5a22ff8f1b4b2',
				'label'             => 'Copy',
				'name'              => 'lead-in_copy',
				'type'              => 'textarea',
				'instructions'      => '3-4 concise sentences describing the value of or encouraging site visitors to join in whatever piece of NAACP\'s work you\'re promoting.',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => 4,
				'new_lines'         => '',
			),
			array(
				'key'               => 'field_5a24f70756074',
				'label'             => 'Include call-to-action links?',
				'name'              => '',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'Yes' => 'Yes',
					'No'  => 'No',
				),
				'allow_null'        => 0,
				'other_choice'      => 0,
				'save_other_choice' => 0,
				'default_value'     => 'No',
				'layout'            => 'vertical',
				'return_format'     => 'value',
			),
			array(
				'key'               => 'field_5a2300477acb0',
				'label'             => 'CTA Links',
				'name'              => 'lead-in_CTA',
				'type'              => 'group',
				'instructions'      => 'These are the big 3 call-to-action links at the end of the lead-in section.',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5a24f70756074',
							'operator' => '==',
							'value'    => 'Yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5a23026732ed5',
						'label'             => 'Link 1',
						'name'              => 'lead-in_link-1',
						'type'              => 'link',
						'instructions'      => 'First call-to-action link',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
					),
					array(
						'key'               => 'field_5a23028732ed6',
						'label'             => 'Link 2',
						'name'              => 'lead-in_link-2',
						'type'              => 'link',
						'instructions'      => 'Second call-to-action link',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
					),
					array(
						'key'               => 'field_5a23029432ed7',
						'label'             => 'Link 3',
						'name'              => 'lead-in_link-3',
						'type'              => 'link',
						'instructions'      => 'Third call-to-action link',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'page',
					'operator' => '==',
					'value'    => '8',
				),
			),
			array(
				array(
					'param'    => 'page',
					'operator' => '==',
					'value'    => '10',
				),
			),
			array(
				array(
					'param'    => 'page',
					'operator' => '==',
					'value'    => '77',
				),
			),
			array(
				array(
					'param'    => 'page',
					'operator' => '==',
					'value'    => '79',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => array(
			0 => 'the_content',
		),
		'active'                => 1,
		'description'           => 'Lead-in copy template for pages',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5a22fdd7f2b9e',
		'title'                 => 'Make a Donation',
		'fields'                => array(
			array(
				'key'               => 'field_5a2303fad343b',
				'label'             => 'Donation Form Link',
				'name'              => 'donation_form_link',
				'type'              => 'text',
				'instructions'      => 'Code to automatically load form created in GravityForms. If you need to make a change there, find the form in the GravityForms plugin.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5a23074dabbe0',
				'label'             => 'Direct Donation Information',
				'name'              => 'direct_donation_info',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'block',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5a23076babbe1',
						'label'             => 'Mailing instructions',
						'name'              => 'donate_mail-instructions',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => 'How do I send in a donation?',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_5a2307b4abbe2',
						'label'             => 'Mailing address',
						'name'              => 'donate_mailing-address',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => 'Mailing address here...',
						'maxlength'         => '',
						'rows'              => 3,
						'new_lines'         => 'br',
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'page',
					'operator' => '==',
					'value'    => '8',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => array(
			0 => 'the_content',
		),
		'active'                => 1,
		'description'           => 'Page section with donation form and information',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5a24763325e95',
		'title'                 => 'Inspirational Footer CTA',
		'fields'                => array(
			array(
				'key'               => 'field_5a24763dc86ad',
				'label'             => 'Message',
				'name'              => 'footer_message',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => 'Inspirational closing call-to-action, here...',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5a247666c86ae',
				'label'             => 'CTA Links',
				'name'              => 'footer_cta-links',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5a247680c86af',
						'label'             => 'Link 1',
						'name'              => 'link_1',
						'type'              => 'link',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
					),
					array(
						'key'               => 'field_5a247693c86b0',
						'label'             => 'Link 2',
						'name'              => 'link_2',
						'type'              => 'link',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'post',
				),
			),
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'page',
				),
			),
		),
		'menu_order'            => 100,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => 1,
		'description'           => '',
	) );

endif;